xbuildlanguage: csharp
solution: AliceNet.sln
dotnet: 2.0.0
sudo: required
mono: latest
install:
  - mono ./.paket/paket.bootstrapper.exe
  - mono ./.paket/paket.exe restore
script:
  - dotnet build
  - dotnet test .\Tests