language: csharp
solution: AliceMQ.sln
install:
  - mono ./.paket/paket.bootstrapper.exe
  - mono ./.paket/paket.exe restore
script:
  - xbuild AliceMQ.sln
  - mono ./packages/xunit.runner.console/tools/xunit.console.x86.exe ./AliceMQ.Tests/bin/Debug/AliceMQ.Tests.dll
