language: csharp
solution: AliceMQ.sln
dotnet: 2.0.0
sudo: required
mono: latest
branches:
  only:
    - master
install:
  - mono ./.paket/paket.bootstrapper.exe
  - mono ./.paket/paket.exe update
  - mono ./.paket/paket.exe restore
script:
  - fsi build.fsx